// Error code -> [Dari, Pashto, English]
export const ERROR_MESSAGES: Record<string, [string, string, string]> = {
  unauthenticated: ["لطفاً دوباره وارد شوید", "بیا ننوځئ", "Please sign in again"],
  forbidden: ["شما صلاحیت انجام این عملیات را ندارید", "تاسو د دې عملیاتو صلاحیت نه لرئ", "You do not have permission for this action"],
  unbalanced: ["سند بیلانس نیست: مجموع دبت باید با مجموع کردت مساوی باشد", "سند بیلانس نه دی", "Entry is unbalanced: total debit must equal total credit"],
  insufficient_funds: ["موجودی حساب کافی نیست", "د حساب موجودي کافي نه ده", "Insufficient balance"],
  duplicate: ["این نمبر / کود قبلاً ثبت شده است", "دا شمېره مخکې ثبت شوې", "This number/code already exists"],
  reference: ["این رکورد به رکوردهای دیگر وابسته است و قابل حذف نیست", "دا ریکارډ په نورو پورې تړلی دی", "Record is referenced by other records and cannot be deleted"],
  not_found: ["رکورد یافت نشد", "ریکارډ ونه موندل شو", "Record not found"],
  invalid_amount: ["مبلغ نامعتبر است", "مبلغ ناسم دی", "Invalid amount"],
  invalid_input: ["معلومات وارد شده نامعتبر است", "ورودي معلومات ناسم دي", "Invalid input"],
  // Case validation errors
  invalid_case_date: ["تاریخ افتتاح دوسیه نامعتبر است", "د دوسیې د پرانیستلو نېټه ناسم ده", "Invalid case opening date"],
  invalid_case_fee: ["مبلغ خدمات نامعتبر است", "د خدمت فیس ناسم دی", "Invalid case service fee"],
  invalid_case_discount: ["مبلغ تخفیف نامعتبر است یا از فیس بیشتر است", "د تخفیف مبلغ ناسم دی یا له فیس څخه زیات دی", "Invalid case discount"],
  invalid_case_service: ["خدمت انتخاب‌شده معتبر نیست", "ټاکل شوی خدمت ناسم دی", "Selected service is invalid"],
  invalid_case_employee: ["کارمند مسئول معتبر نیست", "مسئول کارکوونکی ناسم دی", "Responsible employee is invalid"],

  already_finalized: ["این رکورد قبلاً نهایی شده است", "دا ریکارډ مخکې نهایي شوی", "Record already finalized"],
  already_posted: ["این سند قبلاً پست شده است", "دا سند مخکې پوسټ شوی", "Entry already posted"],
  not_posted: ["فقط اسناد پست شده قابل معکوس‌سازی هستند", "یوازې پوسټ شوي اسناد معکوس کېدای شي", "Only posted entries can be reversed"],
  cannot_edit_final: ["رکورد نهایی شده قابل ویرایش نیست", "نهایي شوی ریکارډ نه سمېږي", "Finalized records cannot be edited"],
  cannot_edit_posted: ["سند پست شده قابل ویرایش نیست؛ از ثبت معکوس استفاده کنید", "پوسټ شوی سند نه سمېږي", "Posted entries cannot be edited; use a reversing entry"],
  no_exchange_rate: ["نرخ تبادله برای این اسعار تنظیم نشده است", "د دې اسعارو نرخ نه دی ټاکل شوی", "No exchange rate configured for this currency"],
  cash_account_required: ["حساب صندوق را انتخاب کنید", "د صندوق حساب وټاکئ", "Select a cash account"],
  bank_account_required: ["حساب بانکی را انتخاب کنید", "بانکي حساب وټاکئ", "Select a bank account"],
  customer_required: ["برای فروش نسیه، مشتری الزامی است", "د پور لپاره پیرودونکی اړین دی", "Customer is required for credit sales"],
  customer_not_found: ["مشتری یافت نشد", "پیرودونکی ونه موندل شو", "Customer not found"],
  cash_account_not_found: ["حساب صندوق یافت نشد یا غیرفعال است", "د صندوق حساب ونه موندل شو", "Cash account not found or inactive"],
  bank_account_not_found: ["حساب بانکی یافت نشد یا غیرفعال است", "بانکي حساب ونه موندل شو", "Bank account not found or inactive"],
  same_account: ["حساب مبدأ و مقصد نمی‌تواند یکی باشد", "سرچینه او موخه یو شان نه شي کېدای", "Source and destination cannot be the same"],
  invalid_transition: ["این تغییر وضعیت مجاز نیست", "دا د حالت بدلون جواز نه لري", "This status transition is not allowed"],
  invalid_credentials: ["ایمیل یا رمز عبور نادرست است", "بریښنالیک یا پټنوم ناسم دی", "Invalid email or password"],
  email_exists: ["این ایمیل قبلاً ثبت شده است", "دا بریښنالیک مخکې ثبت شوی", "Email already registered"],
  weak_password: ["رمز عبور باید حداقل ۶ حرف باشد", "پټنوم باید لږ تر لږه ۶ توري وي", "Password must be at least 6 characters"],
  last_admin: ["حداقل یک مدیر سیستم باید باقی بماند", "لږ تر لږه یو مدیر باید پاتې شي", "At least one admin must remain"],
  file_too_large: ["حجم فایل نباید بیشتر از ۵ مگابایت باشد", "فایل باید تر ۵ MB کم وي", "File must be smaller than 5 MB"],
  invalid_backup: ["فایل پشتیبان نامعتبر است", "بیک اپ فایل ناسم دی", "Invalid backup file"],
  not_demo: ["این عملیات فقط برای سازمان نمونه مجاز است", "دا یوازې د نمونه سازمان لپاره دی", "Only allowed for the demo organization"],
  server_error: ["خطای داخلی سرور", "د سرور داخلي تېروتنه", "Internal server error"],
  missing_account: ["حساب سیستمی در چارت حسابات یافت نشد", "سیسټمي حساب ونه موندل شو", "System account missing in chart of accounts"],
  official_source_required: ["منبع رسمی معتبر .gov.af الزامی است", "باوري رسمي .gov.af سرچینه اړینه ده", "A valid official .gov.af source is required"],
  legal_review_required: ["این مورد نیازمند بررسی قانونی است و قابل تأیید نهایی نیست", "دا موضوع قانوني ارزونې ته اړتیا لري او وروستی تایید نه شي کېدای", "This item requires legal review and cannot be finally approved"],
  amount_exceeds_due: ["مبلغ از باقی‌مانده قابل پرداخت بیشتر است", "مبلغ له پاتې پور څخه زیات دی", "Amount exceeds the outstanding balance"],
  approval_required: ["برای این مورد منظوری لازم است", "د دې مورد لپاره منظوري اړینه ده", "Approval is required for this item"],
  forbidden_admin: ["فقط مدیر سیستم می‌تواند مدیر سیستم دیگر را مدیریت کند", "یوازې د سیسټم مدیر بل مدیر اداره کولی شي", "Only a system admin can manage another admin"],
  forbidden_finalize: ["شما صلاحیت نهایی‌سازی را ندارید", "تاسو د نهایي کولو صلاحیت نه لرئ", "You do not have permission to finalize"],
  forbidden_post: ["شما صلاحیت ثبت نهایی سند حسابداری را ندارید", "تاسو د محاسبوي سند د پوسټ صلاحیت نه لرئ", "You do not have permission to post journal entries"],
  forbidden_source: ["این منبع رسمی نیست", "دا رسمي سرچینه نه ده", "This is not an official source"],
  case_has_history: ["این دوسیه دارای اسناد، رسید یا سابقه مالی است و قابل حذف نیست", "دا دوسیه اسناد، رسید یا مالي مخینه لري او نه شي ړنګېدای", "This case has linked documents, receipts, or financial history and cannot be deleted"],
};
