'use client';

import { useEffect, useState } from 'react';
import { loadDabRenewalForm, saveDabRenewalForm } from '@/lib/dabRenewalFormStore';

type Shareholder = { id: string; name: string; fatherName: string; identityNo: string; shares: string; province: string; district: string; nahia: string };
type Representative = { id: string; name: string; fatherName: string; identityNo: string; phone: string; province: string; district: string; nahia: string; market: string; shopNo: string; location: string; agencyNo: string };
type BankAccount = { id: string; name: string; number: string; bank: string };
type Signature = { id: string; name: string; fingerprint: string; signature: string; date: string };

type RenewalForm = {
  companyName: string; licenseNo: string; licenseDate: string;
  shareholders: Shareholder[];
  companyProvince: string; companyDistrict: string; companyNahia: string; companyMarket: string; companyShop: string; companyNameEnglish: string; email: string; phone: string;
  licenseDetails: string;
  representatives: Representative[];
  bankAccounts: BankAccount[];
  majorChanges: 'yes' | 'no' | '';
  changeDetails: string;
  activeLastYear: 'yes' | 'no' | '';
  inactiveReason: string;
  legalClaim: 'yes' | 'no' | '';
  legalClaimDetails: string;
  signatures: Signature[];
  evaluatorName: string; evaluatorSignature: string; evaluatorDate: string;
};

const blank = (): RenewalForm => ({
  companyName: '', licenseNo: '', licenseDate: '', shareholders: [], companyProvince: '', companyDistrict: '', companyNahia: '', companyMarket: '', companyShop: '', companyNameEnglish: '', email: '', phone: '', licenseDetails: '', representatives: [], bankAccounts: [], majorChanges: '', changeDetails: '', activeLastYear: '', inactiveReason: '', legalClaim: '', legalClaimDetails: '', signatures: [], evaluatorName: '', evaluatorSignature: '', evaluatorDate: ''
});

const id = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const Field = ({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; type?: string }) => <label className="block"><span className="mb-1 block text-sm font-bold text-slate-700">{label}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-700" /></label>;
const Text = ({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) => <label className="block"><span className="mb-1 block text-sm font-bold text-slate-700">{label}</span><textarea value={value} onChange={e => onChange(e.target.value)} rows={3} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-700" /></label>;

export default function DabLicenseRenewalOfficialForm({ companyId = 'default' }: { companyId?: string }) {
  const [form, setForm] = useState<RenewalForm>(blank);
  const [saved, setSaved] = useState(false);
  useEffect(() => { let active = true; void loadDabRenewalForm(companyId, 'license-renewal').then(saved => { if (active && saved?.values) setForm({ ...blank(), ...(saved.values as Partial<RenewalForm>) }); }).catch(() => { if (active) setSaved(false); }); return () => { active = false; }; }, [companyId]);
  const set = <K extends keyof RenewalForm>(key: K, value: RenewalForm[K]) => setForm(f => ({ ...f, [key]: value }));
  const save = async () => { try { await saveDabRenewalForm(companyId, 'license-renewal', form as unknown as Record<string, unknown>); setSaved(true); } catch { setSaved(false); } };
  const add = <K extends 'shareholders' | 'representatives' | 'bankAccounts' | 'signatures'>(key: K) => {
    const item = key === 'shareholders' ? { id: id(), name: '', fatherName: '', identityNo: '', shares: '', province: '', district: '', nahia: '' } : key === 'representatives' ? { id: id(), name: '', fatherName: '', identityNo: '', phone: '', province: '', district: '', nahia: '', market: '', shopNo: '', location: '', agencyNo: '' } : key === 'bankAccounts' ? { id: id(), name: '', number: '', bank: '' } : { id: id(), name: '', fingerprint: '', signature: '', date: '' };
    set(key, [...form[key], item] as RenewalForm[K]);
  };
  const remove = (key: 'shareholders' | 'representatives' | 'bankAccounts' | 'signatures', itemId: string) => set(key, form[key].filter((x: { id: string }) => x.id !== itemId) as RenewalForm[typeof key]);
  const updateRow = (key: 'shareholders' | 'representatives' | 'bankAccounts' | 'signatures', itemId: string, field: string, value: string) => set(key, form[key].map((row: Record<string, unknown>) => row.id === itemId ? { ...row, [field]: value } : row) as RenewalForm[typeof key]);

  return <main dir="rtl" className="mx-auto max-w-7xl space-y-6 rounded-2xl bg-white p-5 text-slate-900 shadow-sm print:shadow-none">
    <header className="border-b-2 border-slate-900 pb-5 text-center"><p className="font-black">د افغانستان بانک</p><p className="font-bold">آمریت عمومی نظارت از مؤسسات مالی غیر بانکی</p><p className="font-bold">مدیریت جوازدهی</p><h1 className="mt-3 text-2xl font-black">فورم درخواستی تمدید جواز شرکت صرافی و خدمات پولی</h1><p className="mt-2 text-sm text-slate-600">فورم دیجیتال مطابق ساختار سند ارائه‌شده DAB</p></header>
    <section className="rounded-xl border border-slate-300 p-4"><h2 className="mb-3 text-lg font-black">رهنمود عمومی</h2><p className="text-sm leading-7">این فورم باید با حضور سهمدار/سهمداران در مقابل کارمند مسئول در مدیریت جوازدهی آمریت عمومی نظارت از مؤسسات مالی غیر بانکی یا در حضور کارمند مسئول در آمریت زون مربوط/مدیریت نمایندگی د افغانستان بانک در ولایات امضاء و شصت‌گذاری گردد. کارمند مسئول باید مطمئن شود که فورم حسب اسناد و مدارک مربوط خانه‌پری و توسط خود سهمدار/سهمداران امضاء و شصت‌گذاری می‌گردد.</p></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">بخش اول: مشخصات سهمدار</h2><div className="grid gap-3 md:grid-cols-3"><Field label="نام شرکت" value={form.companyName} onChange={v => set('companyName', v)} /><Field label="شماره جواز" value={form.licenseNo} onChange={v => set('licenseNo', v)} /><Field label="تاریخ اخذ جواز" type="date" value={form.licenseDate} onChange={v => set('licenseDate', v)} /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1100px] border-collapse text-sm"><thead><tr>{['شماره','شهرت / نام','نام پدر','شماره تذکره','فیصدی سهم','ولایت','ولسوالی','ناحیه','عملیات'].map(h => <th key={h} className="border border-slate-300 bg-slate-100 p-2">{h}</th>)}</tr></thead><tbody>{form.shareholders.map((r, i) => <tr key={r.id}>{[ ['name','نام'],['fatherName','نام پدر'],['identityNo','شماره تذکره'],['shares','فیصدی سهم'],['province','ولایت'],['district','ولسوالی'],['nahia','ناحیه'] ].map(([f]) => <td key={f} className="border border-slate-300 p-1"><input value={String(r[f as keyof Shareholder])} onChange={e => updateRow('shareholders', r.id, f, e.target.value)} className="w-full rounded border p-1.5" /></td>)}<td className="border border-slate-300 p-1 text-center"><span className="mr-2">{i + 1}</span><button type="button" onClick={() => remove('shareholders', r.id)} className="text-red-700">حذف</button></td></tr>)}</tbody></table></div><button type="button" onClick={() => add('shareholders')} className="mt-3 rounded-lg border border-blue-700 px-4 py-2 text-sm font-bold text-blue-800">+ افزودن سهمدار</button></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">آدرس شرکت صرافی و خدمات پولی</h2><div className="grid gap-3 md:grid-cols-3"><Field label="ولایت" value={form.companyProvince} onChange={v => set('companyProvince', v)} /><Field label="ولسوالی" value={form.companyDistrict} onChange={v => set('companyDistrict', v)} /><Field label="ناحیه" value={form.companyNahia} onChange={v => set('companyNahia', v)} /><Field label="مارکیت" value={form.companyMarket} onChange={v => set('companyMarket', v)} /><Field label="منزل و شماره دکان" value={form.companyShop} onChange={v => set('companyShop', v)} /><Field label="نام شرکت" value={form.companyName} onChange={v => set('companyName', v)} /><Field label="نام شرکت به انگلیسی" value={form.companyNameEnglish} onChange={v => set('companyNameEnglish', v)} /><Field label="ایمیل آدرس" type="email" value={form.email} onChange={v => set('email', v)} /><Field label="شماره تماس" value={form.phone} onChange={v => set('phone', v)} /></div></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">بخش دوم: مشخصات جواز فعالیت</h2><Text label="مشخصات جواز فعالیت" value={form.licenseDetails} onChange={v => set('licenseDetails', v)} /><h3 className="mt-5 mb-2 font-black">مشخصات نمایندگی‌ها و کارمندان رسمی مسئول</h3><div className="space-y-4">{form.representatives.map((r, i) => <div key={r.id} className="rounded-xl border border-slate-300 p-3"><div className="mb-2 flex justify-between"><b>نمایندگی {i + 1}</b><button type="button" onClick={() => remove('representatives', r.id)} className="text-red-700">حذف</button></div><div className="grid gap-3 md:grid-cols-3">{(['name','fatherName','identityNo','phone','province','district','nahia','market','shopNo','location','agencyNo'] as const).map(f => <Field key={f} label={({name:'اسم',fatherName:'ولد',identityNo:'نمبر تذکره',phone:'شماره تماس',province:'ولایت',district:'ولسوالی',nahia:'ناحیه',market:'مارکیت',shopNo:'نمبر دکان',location:'موقعیت نمایندگی',agencyNo:'شماره نمایندگی طبق جواز'} as Record<string,string>)[f]} value={r[f]} onChange={v => updateRow('representatives', r.id, f, v)} />)}</div></div>)}</div><button type="button" onClick={() => add('representatives')} className="mt-3 rounded-lg border border-blue-700 px-4 py-2 text-sm font-bold text-blue-800">+ افزودن نمایندگی</button><h3 className="mt-6 mb-2 font-black">حسابات بانکی شرکت و نمایندگی‌ها</h3><div className="space-y-3">{form.bankAccounts.map((r, i) => <div key={r.id} className="grid gap-3 rounded-xl border border-slate-300 p-3 md:grid-cols-4"><Field label={`شماره ${i + 1}`} value={String(i + 1)} onChange={() => undefined} /><Field label="نام حساب بانکی" value={r.name} onChange={v => updateRow('bankAccounts', r.id, 'name', v)} /><Field label="نمبر حساب" value={r.number} onChange={v => updateRow('bankAccounts', r.id, 'number', v)} /><div><Field label="بانک مربوطه" value={r.bank} onChange={v => updateRow('bankAccounts', r.id, 'bank', v)} /><button type="button" onClick={() => remove('bankAccounts', r.id)} className="mt-1 text-xs font-bold text-red-700">حذف حساب</button></div></div>)}</div><button type="button" onClick={() => add('bankAccounts')} className="mt-3 rounded-lg border border-blue-700 px-4 py-2 text-sm font-bold text-blue-800">+ افزودن حساب بانکی</button></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">بخش سوم: تغییرات مطالبه‌شده حین تمدید جواز فعالیت</h2><p className="mb-3 text-sm leading-7">آیا شرکت حین پروسه تمدید خواهان تغییرات عمده مانند تغییر محل فعالیت، تغییر نام تجارتی، انتقال مالکیت، حذف یا ازدیاد سهمدار، تغییر تشکیلات، تغییر نوع خدمات، تغییر ضامن، تغییر نماینده یا تغییر نمایندگی می‌باشد؟</p><div className="flex gap-6"><label><input type="radio" checked={form.majorChanges === 'yes'} onChange={() => set('majorChanges','yes')} /> بلی</label><label><input type="radio" checked={form.majorChanges === 'no'} onChange={() => set('majorChanges','no')} /> نخیر</label></div><div className="mt-3"><Text label="شرح تغییر مورد نظر" value={form.changeDetails} onChange={v => set('changeDetails', v)} /></div></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">پرسش‌های اجباری سهمدار/سهمداران</h2><div className="space-y-5"><div><p className="mb-2 font-bold">1- آیا شرکت از سال گذشته تا اکنون فعالیت داشته است؟</p><div className="flex gap-6"><label><input type="radio" checked={form.activeLastYear === 'yes'} onChange={() => set('activeLastYear','yes')} /> بلی</label><label><input type="radio" checked={form.activeLastYear === 'no'} onChange={() => set('activeLastYear','no')} /> نخیر</label></div><Text label="دلایل عدم فعالیت" value={form.inactiveReason} onChange={v => set('inactiveReason', v)} /></div><div><p className="mb-2 font-bold">2- آیا علیه شما یا شرکت‌هایی که در آن سهمدار هستید دعوی صورت گرفته است؟</p><div className="flex gap-6"><label><input type="radio" checked={form.legalClaim === 'yes'} onChange={() => set('legalClaim','yes')} /> بلی</label><label><input type="radio" checked={form.legalClaim === 'no'} onChange={() => set('legalClaim','no')} /> نخیر</label></div><Text label="شرح و دلایل" value={form.legalClaimDetails} onChange={v => set('legalClaimDetails', v)} /></div></div></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">بخش چهارم: شصت و امضاء سهمداران</h2><p className="mb-4 text-sm leading-7">بدین وسیله اقرار می‌دارم/می‌داریم که معلومات ارائه‌شده در این فورم درست و مکمل می‌باشد. در صورتی‌که معلومات نادرست باشد یا تخلف در آن دیده شود، حاضرم/حاضریم طبق قوانین و مقررات نافذه کشور با من/ما برخورد صورت گیرد.</p><div className="space-y-3">{form.signatures.map((r, i) => <div key={r.id} className="grid gap-3 rounded-xl border border-slate-300 p-3 md:grid-cols-5"><Field label={`نام ${i + 1}`} value={r.name} onChange={v => updateRow('signatures', r.id, 'name', v)} /><Field label="شصت" value={r.fingerprint} onChange={v => updateRow('signatures', r.id, 'fingerprint', v)} /><Field label="امضاء" value={r.signature} onChange={v => updateRow('signatures', r.id, 'signature', v)} /><Field label="تاریخ" type="date" value={r.date} onChange={v => updateRow('signatures', r.id, 'date', v)} /><button type="button" onClick={() => remove('signatures', r.id)} className="self-end text-red-700">حذف</button></div>)}</div><button type="button" onClick={() => add('signatures')} className="mt-3 rounded-lg border border-blue-700 px-4 py-2 text-sm font-bold text-blue-800">+ افزودن سهمدار برای امضاء</button></section>
    <section><h2 className="mb-3 border-b border-slate-300 pb-2 text-xl font-black">بخش پنجم: تکمیل توسط کارمند مسئول د افغانستان بانک</h2><div className="space-y-2 rounded-xl border border-slate-300 p-4 text-sm leading-7"><label className="block"><input type="checkbox" /> اصل جواز فعالیت تسلیم گردیده است.</label><label className="block"><input type="checkbox" /> استعلام جرم مالیاتی و جنایی کارمندان و نماینده‌ها بررسی گردیده است.</label><label className="block"><input type="checkbox" /> رفع مسئولیت مالیاتی شرکت بررسی گردیده است.</label><label className="block"><input type="checkbox" /> تضمین‌کننده دارای جواز فعال و اسناد لازم می‌باشد و فورم تضمین ارائه گردیده است.</label><label className="block"><input type="checkbox" /> مبلغ تضمین پولی شرکت حسب اصول تکمیل می‌باشد.</label><label className="block"><input type="checkbox" /> تمام شرایط و معیارهای تمدید جواز تکمیل گردیده است.</label></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Field label="اسم ارزیابی‌کننده" value={form.evaluatorName} onChange={v => set('evaluatorName', v)} /><Field label="امضاء ارزیابی‌کننده" value={form.evaluatorSignature} onChange={v => set('evaluatorSignature', v)} /><Field label="تاریخ" type="date" value={form.evaluatorDate} onChange={v => set('evaluatorDate', v)} /></div></section>
    <footer className="sticky bottom-0 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-white/95 py-4 backdrop-blur print:hidden"><span className="text-sm font-bold text-emerald-700">{saved ? 'معلومات فورم ذخیره شد.' : 'فورم آماده خانه‌پری است.'}</span><div className="flex gap-2"><button type="button" onClick={() => window.print()} className="rounded-lg border border-slate-400 px-5 py-2 font-bold">چاپ</button><button type="button" onClick={save} className="rounded-lg bg-blue-800 px-5 py-2 font-bold text-white">ذخیره فورم</button></div></footer>
  </main>;
}
