export const barakatullahGhafouriProfile = {
  legalName: 'شرکت صرافی و خدمات پولی برکت‌الله غفوری (سهامی خاص)',
  formerName: 'شرکت صرافی و خدمات پولی ستاره آسیا',
  englishName: 'Barakatullah Ghafouri Money Exchange & MSP Services Co.',
  licenseNo: 'DAB/7-0965',
  province: 'کندز',
  district: 'مرکز',
  neighborhood: 'ناحیه 3',
  market: 'مومند مارکیت',
  floor: 'منزل دوم',
  shopNo: '301',
  address: 'مومند مارکیت، منزل دوم، دکان نمبر 301، ولایت کندز',
  phone: '0799681111 / 0749340000',
  email: 'info@barakatullah-exchange.af',
  licenseExpiryDate: '1405/03/13',
  meetingPlace: 'مومند مارکیت، منزل 2، دکان 301، ولایت کندز',
  meetingNo: '1405/MM-101',
  meetingDate: '1405/02/15',
  meetingTime: '10:00 AM',
  letterNo: '1405/BG-105',
  letterDate: '1405/02/20',
  articlesDate: 'جوزا 1405',
  branches: [
    { no: '1', location: 'کابل', market: 'مارکیت سرای شهزاده', shopNo: '188', district: 'ناحیه اول', representative: 'اجمل احمدی', representativeFather: 'نورآغا', identityNo: '1400-107-46338', phone: '', education: 'لیسانس', staff: [
      { name: 'محمد بشیر', fatherName: 'عبدالکریم', identityNo: '1398-1102-45211', education: '۱۴ پاس', tin: '9012345678' },
      { name: 'احسان‌الله', fatherName: 'غلام‌حضرت', identityNo: '1401-0901-33214', education: 'لیسانس', tin: '9022341122' },
      { name: 'نجیب‌الله', fatherName: 'فضل‌احمد', identityNo: '1402-0504-88912', education: 'دوازدهم', tin: '' },
    ] },
    { no: '2', location: 'تخار', market: 'صرافی صرافان', shopNo: '12', district: 'تالقان', village: 'مرکز', representative: 'رحمت‌الله رحیمی', representativeFather: 'محمد مراد', identityNo: '1400-1305-16532', phone: '0788165320', education: 'بکلوریا (۱۲ پاس)', staff: [{ name: 'عبیدالله', fatherName: '', identityNo: '', education: '', role: 'خزانه‌دار' }] },
    { no: '3', location: 'کشم، بدخشان', market: '', shopNo: '', district: '', village: '', representative: 'عتیق‌الله', representativeFather: '', identityNo: '', phone: '', education: '', staff: [] },
    { no: '4', location: 'امام‌صاحب', market: '', shopNo: '', district: '', village: '', representative: 'محمدیوسف', representativeFather: '', identityNo: '', phone: '', education: '', staff: [{ name: 'عبدالمجید', fatherName: '', identityNo: '', education: '', role: 'خزانه‌دار' }] },
  ],
  representatives: [
    { location: 'کابل', representative: 'اجمل احمدی' },
    { location: 'تخار', representative: 'رحمت‌الله رحیمی' },
    { location: 'کشم، بدخشان', representative: 'عتیق‌الله' },
    { location: 'امام‌صاحب', representative: 'محمدیوسف' },
  ],
  shareholders: [{ name: 'برکت‌الله غفوری', fatherName: 'عبدالغفور', identityNo: '1399-1104-55522', sharePercent: 100, capital: 30000000, education: 'لیسانس' }],
  formerShareholders: [{ name: 'حبیب‌الرحمن غفوری', identityNo: '98712-1104-0043215', transferredPercent: 100 }],
  board: {
    chair: { name: 'بسم‌الله شیرزی', fatherName: 'دوستمحمد', identityNo: '1402-0902-45188', education: 'لیسانس' },
    formerChair: { name: 'بقیت‌الله', identityNo: '65431-1201-0098761' },
    members: [
      { name: 'برکت‌الله غفوری', fatherName: 'عبدالغفور', identityNo: '1399-1104-55522', education: 'لیسانس' },
      { name: 'عظیم‌الله رحمانی', fatherName: 'محمد آجان', identityNo: '1399-1105-35806', education: 'لیسانس' },
    ],
  },
  management: [
    { name: 'برکت‌الله غفوری', fatherName: 'عبدالغفور', role: 'سهمدار اصلی و عضو هیئت نظار', identityNo: '1399-1104-55522', education: 'لیسانس' },
    { name: 'بسم‌الله شیرزی', fatherName: 'دوستمحمد', role: 'رئیس هیئت نظار', identityNo: '1402-0902-45188', education: 'لیسانس' },
    { name: 'برکت‌الله غفوری', fatherName: 'عبدالغفور', role: 'عضو هیئت نظار', identityNo: '1399-1104-55522', education: 'لیسانس', tin: '9005155800' },
    { name: 'عظیم‌الله رحمانی', fatherName: 'محمد آجان', role: 'عضو هیئت نظار', identityNo: '1399-1105-35806', education: 'لیسانس' },
    { name: 'صالح‌محمد رحیمی', fatherName: 'عبدالرحیم', role: 'مسئول عملیاتی', identityNo: '1402-0201-48424', education: 'لیسانس', tin: '9020613858' },
  ],
  complianceOfficer: { name: 'عبدالعزیز مهرزاد', fatherName: 'عبدالخلیل', identityNo: '72198-0300-1401', education: 'لیسانس اداره و تجارت' },
  meetingAttendees: [
    { name: 'برکت‌الله ولد عبدالغفور', role: 'سهمدار اصلی، مالک 100٪ سرمایه و رئیس مجمع', identityNo: '55522-1104-1001399' },
    { name: 'بسم‌الله شیرزی', role: 'رئیس جدید هیئت نظار', identityNo: '34210-0201-0087654' },
    { name: 'برکت‌الله غفوری', role: 'عضو هیئت نظار و نماینده سهمداران', identityNo: '55522-1104-1001399' },
    { name: 'عظیم‌الله رحمانی', role: 'عضو هیئت نظار و مشاور حقوقی', identityNo: '12980-1504-0054321' },
    { name: 'اجمل احمدی', role: 'نماینده جدید و رسمی شعبه کابل', identityNo: '43210-1101-0065432' },
    { name: 'حبیب‌الرحمن غفوری', role: 'سهمدار سابق (انتقال‌دهنده سهم)', identityNo: '98712-1104-0043215' },
    { name: 'بقیت‌الله', role: 'رئیس سابق هیئت نظار (مستعفی)', identityNo: '65431-1201-0098761' },
  ],
  guarantors: [
    { name: 'ولی محمد حبیبی ذاخیل', fatherName: 'وحید الله', identityNo: '1402-0900-08912', phone: '0744761943', province: 'کندز', district: 'مرکز', neighborhood: 'مرکز کندز', village: 'مرکز', business: 'شرکت صرافی و خدمات پولی ولی محمد ذاخیل' },
    { name: 'عبدالقادر', fatherName: '', identityNo: '', phone: '', province: 'کندز', district: 'مرکز', neighborhood: 'مرکز', village: '', business: 'عبدالقادر' },
    { name: '', fatherName: '', identityNo: '', phone: '', province: '', district: '', neighborhood: '', village: '', business: '' },
  ],
  guarantorBusiness: { name: 'عبدالقادر', type: 'صرافی و خدمات پولی (MSP)', licenseNo: 'DAB/7-1112', phone: '۰۷۴۴۷۶۱۹۴۳', expiryDate: '24-04-1406', email: '', issuer: 'دافغانستان بانک', address: 'ولایت کندز، مارکیت مهمند، منزل دوم، دکان نمبر ۵۴' },
  resolutions: [
    'انتقال 100٪ اسهام حبیب‌الرحمن غفوری به برکت‌الله غفوری',
    'تغییر نام شرکت از «ستاره آسیا» به «برکت‌الله غفوری»',
    'تغییر نماینده کابل از برکت‌الله غفوری به اجمل احمدی',
    'تغییر رئیس هیئت نظار از بقیت‌الله به بسم‌الله شیرزی',
    'تمدید جواز فعالیت مرکز و چهار نمایندگی ولایتی',
    'ارزیابی انطباق با قوانین مبارزه با پولشویی و عواید ناشی از جرایم (AML/CFT)',
  ],
  agenda: [
    'انتقال و واگذاری کلیه اسهام و سرمایه حبیب‌الرحمن غفوری به برکت‌الله غفوری (تثبیت 100٪ اسهام).',
    'تغییر نام رسمی شرکت از «شرکت صرافی و خدمات پولی ستاره آسیا» به «شرکت صرافی و خدمات پولی برکت‌الله غفوری».',
    'تغییر و تعیین نماینده رسمی شعبه کابل از برکت‌الله غفوری به اجمل احمدی.',
    'تغییر و تعیین رئیس هیئت نظار از محترم بقیت‌الله به محترم بسم‌الله شیرزی.',
    'تمدید جواز فعالیت مرکز صرافی و چهار نمایندگی تابعه در د افغانستان بانک (DAB).',
    'ارزیابی انطباق با قوانین مبارزه با پولشویی و عواید ناشی از جرایم (AML/CFT).',
  ],
  reporting: [
    ['رئیس هیئت نظار', 'سهمدار / مجمع عمومی'],
    ['عضو هیئت نظار', 'سهمدار / مجمع عمومی'],
    ['مسئول عملیاتی', 'عضو هیئت نظار (برکت‌الله)'],
    ['مسئول پیروی از قوانین', 'عبدالعزیز مهرزاد ولد عبدالخلیل — تذکره 72198-0300-1401 — با استقلال انطباقی'],
    ['نماینده‌ها و نمایندگی‌های ولایتی', 'مسئول عملیاتی (صالح‌محمد رحیمی)'],
    ['کارکنان نمایندگی‌ها', 'نماینده مربوطه، زیر نظر مسئول عملیاتی'],
  ],
} as const;
