-- ZIP-derived form identities. No business PII is stored here.
insert into public.official_forms
(organization_id, form_key, agency, form_name, version, source_url, fields, field_mapping, is_official, verification_status, created_by)
select o.id, v.form_key, 'DAB-MSP', v.form_name, 1, 'https://dab.gov.af/dr/فورم-های-خدمات-پولی',
       v.fields::jsonb, v.mapping::jsonb, true, 'source_listed', p.id
from public.organizations o
cross join (select id from public.profiles order by created_at limit 1) p
cross join (values
  ('dab-msp-branch-renewal','فورم تمدید نمایندگی شرکت صرافی و خدمات پولی',
   '[{"key":"company_name","label":"نام شرکت","type":"text","required":true,"mapping":"customer.name"},{"key":"license_number","label":"شماره جواز","type":"text","required":true,"mapping":"customer.primaryLicense.licenseNumber"},{"key":"office_address","label":"موقعیت دفتر مرکزی","type":"textarea","required":true,"mapping":"customer.address"},{"key":"branch_name","label":"نام نمایندگی","type":"text","required":true,"mapping":"customer.selectedBranch.name"},{"key":"branch_number","label":"شماره نمایندگی طبق جواز","type":"text","required":true,"mapping":"customer.selectedBranch.branchNumber"},{"key":"branch_province","label":"ولایت نمایندگی","type":"text","required":true,"mapping":"customer.selectedBranch.province"},{"key":"branch_district","label":"ولسوالی/ناحیه","type":"text","mapping":"customer.selectedBranch.district"},{"key":"branch_area","label":"ناحیه","type":"text","mapping":"customer.selectedBranch.area"},{"key":"branch_market","label":"مارکیت","type":"text","mapping":"customer.selectedBranch.market"},{"key":"branch_shop","label":"منزل و شماره دکان","type":"text","mapping":"customer.selectedBranch.shopNumber"},{"key":"representative_name","label":"اسم نماینده با صلاحیت","type":"text","required":true,"mapping":"customer.selectedBranch.representative.fullName"},{"key":"representative_father","label":"نام پدر نماینده","type":"text","required":true,"mapping":"customer.selectedBranch.representative.fatherName"},{"key":"representative_tazkira","label":"نمبر تذکره نماینده","type":"text","required":true,"mapping":"customer.selectedBranch.representative.nationalId"},{"key":"representative_phone","label":"شماره تماس نماینده","type":"text","required":true,"mapping":"customer.selectedBranch.representative.phone"},{"key":"representative_education","label":"سطح تحصیلات نماینده","type":"text","required":true,"mapping":"customer.selectedBranch.representative.educationLevel"},{"key":"representative_education_field","label":"رشته تحصیلی","type":"text","mapping":"customer.selectedBranch.representative.educationField"},{"key":"license_current","label":"جواز شرکت به روز است","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"representative_id_submitted","label":"کاپی تذکره نماینده تسلیم شده است","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"education_evidence_submitted","label":"سند تحصیلی ارائه شده است","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"signature_date","label":"تاریخ امضاء","type":"date","required":true}]',
   '{"company_name":"customer.name","license_number":"customer.primaryLicense.licenseNumber","office_address":"customer.address","branch_name":"customer.selectedBranch.name","branch_number":"customer.selectedBranch.branchNumber","branch_province":"customer.selectedBranch.province","branch_district":"customer.selectedBranch.district","branch_area":"customer.selectedBranch.area","branch_market":"customer.selectedBranch.market","branch_shop":"customer.selectedBranch.shopNumber","representative_name":"customer.selectedBranch.representative.fullName","representative_father":"customer.selectedBranch.representative.fatherName","representative_tazkira":"customer.selectedBranch.representative.nationalId","representative_phone":"customer.selectedBranch.representative.phone","representative_education":"customer.selectedBranch.representative.educationLevel","representative_education_field":"customer.selectedBranch.representative.educationField"}'),
  ('dab-msp-central-license-checklist','چک لست اسناد و شرایط جواز دفتر مرکزی',
   '[{"key":"company_name","label":"نام شرکت","type":"text","required":true,"mapping":"customer.name"},{"key":"license_number","label":"شماره جواز","type":"text","required":true,"mapping":"customer.primaryLicense.licenseNumber"},{"key":"province","label":"ولایت","type":"text","required":true,"mapping":"customer.province"},{"key":"market","label":"مارکیت","type":"text","mapping":"customer.market"},{"key":"shop_number","label":"شماره دکان","type":"text","mapping":"customer.shopNumber"},{"key":"application_form","label":"فورم درخواستی شصت و امضاء","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"guarantee_receipt","label":"رسید پرداخت آویز تضمین","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"guarantee_form","label":"فورم تضمین سر سهمدار/سهمداران","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"aml_policy","label":"پالیسی مبارزه علیه تطهیر پول و تمویل تروریزم","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"articles_of_association","label":"اساسنامه","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"organization_chart","label":"چارت ساختار تشکیلاتی","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"site_visit","label":"فورم بازدید ساحه","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"tax_clearance","label":"عدم باقیداری مالیاتی","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"software_contract","label":"قرارداد سیستم نرم افزار","type":"select","required":true,"options":["بلی","نخیر"]}]',
   '{"company_name":"customer.name","license_number":"customer.primaryLicense.licenseNumber","province":"customer.province","market":"customer.market","shop_number":"customer.shopNumber"}'),
  ('dab-msp-branch-renewal-checklist','چک لست تمدید جواز نمایندگی',
   '[{"key":"company_name","label":"نام شرکت","type":"text","required":true,"mapping":"customer.name"},{"key":"license_number","label":"شماره جواز","type":"text","required":true,"mapping":"customer.primaryLicense.licenseNumber"},{"key":"province","label":"ولایت نمایندگی","type":"text","required":true,"mapping":"customer.selectedBranch.province"},{"key":"branch_number","label":"شماره نمایندگی","type":"text","required":true,"mapping":"customer.selectedBranch.branchNumber"},{"key":"branch_market","label":"مارکیت","type":"text","required":true,"mapping":"customer.selectedBranch.market"},{"key":"branch_shop","label":"شماره دکان","type":"text","required":true,"mapping":"customer.selectedBranch.shopNumber"},{"key":"original_branch_license","label":"اصل جواز نمایندگی","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"renewal_form","label":"فورم تمدید نمایندگی","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"board_approval","label":"درخواست همراه با تصویب هیئت نظار","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"guarantee_receipt","label":"آویز تضمین تحویلی","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"bank_statement","label":"صورت حساب بانکی سرمایه کاری","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"tax_clearance","label":"عدم مسئولیت مالیاتی","type":"select","required":true,"options":["بلی","نخیر"]},{"key":"guild_response","label":"پاسخ استعلام اتحادیه","type":"select","required":true,"options":["بلی","نخیر"]}]',
   '{"company_name":"customer.name","license_number":"customer.primaryLicense.licenseNumber","province":"customer.selectedBranch.province","branch_number":"customer.selectedBranch.branchNumber","branch_market":"customer.selectedBranch.market","branch_shop":"customer.selectedBranch.shopNumber"}'),
  ('dab-msp-shareholder-employee-info','معلومات عمومی سهمداران و کارمندان شرکت',
   '[{"key":"company_name","label":"نام شرکت","type":"text","required":true,"mapping":"customer.name"},{"key":"record_type","label":"نوع ریکارد","type":"select","required":true,"options":["سهمدار","کارمند"]},{"key":"signature_date","label":"تاریخ","type":"date","required":true}]',
   '{"company_name":"customer.name"}')
) as v(form_key, form_name, fields, mapping) on true
where not exists (
  select 1 from public.official_forms f
  where f.organization_id=o.id and f.form_key=v.form_key
);
